### ISSUE TITLE
Error with mg$plot()

### ISSUE THREAD

**Issue by sjgeisler** [CharlesJB/metagene#65] opened 2016-03-05 23:15 UTC
Hi! I'm new to metagene and have been able to make my way through with the demo data but when I try to implement metagene with my own data keep getting an error when I go to plot. First I set the working directory to the location of the bam and bam.bai files. Then below is what I'm typing in the R console:

> bam_files = c("rep1_sorted.bam", "IN_rep1_sorted.bam")
> regions= promoters_hg19
> design = data.frame(Samples = c("rep1_sorted.bam", "IN_rep1_sorted.bam"), type = c(1,2))
> mg= metagene$new(regions=regions, bam_files=bam_files, force_seqlevels=TRUE, verbose=TRUE)
Prepare bam files...
Prepare regions...
Parse bam files...

  coverages...

> mg$plot(range = c(-1000,1000), title = "metagene plot")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Views’ for signature ‘"NULL"’

Can you tell me what I might be doing wrong?

Thanks in advance!
Sarah

**Comment by CharlesJB** [comment] 2016-03-06 17:00
Hello Sarah,

A few users had a similar problem recently. It can be caused by regions falling outside the range of a chromosome or by different chromosome names between the regions and the bam files. 

Can you give me the result of:
```r
bam_files <- c("rep1_sorted.bam", "IN_rep1_sorted.bam")
lapply(bam_files, function(x) seqlengths(Rsamtools::BamFile(x)))
```

For `promoters_hg19`, I'm guessing you used `data(promoters_hg19)`? If not, could you give me the result of:
```r
seqlenghts(promoters_hg19)
```

**Comment by sjgeisler** [comment] 2016-03-07 10:05
Hi,

Thank you for the quick response! I got the following:

> bam_files <- c("rep1_sorted.bam", "IN_rep1_sorted.bam")
> lapply(bam_files, function(x) seqlengths(Rsamtools::BamFile(x)))

[[1]]
                 chr1                  chr2
chr3                  chr4
            249250621             243199373
198022430             191154276
                 chr5                  chr6
chr7                  chr8
            180915260             171115067
159138663             146364022
                 chr9                 chr10
chr11                 chr12
            141213431             135534747
135006516             133851895
                chr13                 chr14
chr15                 chr16
            115169878             107349540
102531392              90354753
                chr17                 chr18
chr19                 chr20
             81195210              78077248
59128983              63025520
                chr21                 chr22
chrX                  chrY
             48129895              51304566
155270560              59373566
                 chrM  chr1_gl000191_random  chr1_gl000192_random
chr4_gl000193_random
                16571                106433
547496                189789
 chr4_gl000194_random  chr7_gl000195_random  chr8_gl000196_random
chr8_gl000197_random
               191469                182896
38914                 37175
 chr9_gl000198_random  chr9_gl000199_random  chr9_gl000200_random
chr9_gl000201_random
                90085                169874
187035                 36148
chr11_gl000202_random chr17_gl000203_random chr17_gl000204_random
chr17_gl000205_random
                40103                 37498
81310                174588
chr17_gl000206_random chr18_gl000207_random chr19_gl000208_random
chr19_gl000209_random
                41001                  4262
92689                159169
chr21_gl000210_random        chrUn_gl000211        chrUn_gl000212
chrUn_gl000213
                27682                166566
186858                164239
       chrUn_gl000214        chrUn_gl000215        chrUn_gl000216
chrUn_gl000217
               137718                172545
172294                172149
       chrUn_gl000218        chrUn_gl000219        chrUn_gl000220
chrUn_gl000221
               161147                179198
161802                155397
       chrUn_gl000222        chrUn_gl000223        chrUn_gl000224
chrUn_gl000225
               186861                180455
179693                211173
       chrUn_gl000226        chrUn_gl000227        chrUn_gl000228
chrUn_gl000229
                15008                128374
129120                 19913
       chrUn_gl000230        chrUn_gl000231        chrUn_gl000232
chrUn_gl000233
                43691                 27386
40652                 45941
       chrUn_gl000234        chrUn_gl000235        chrUn_gl000236
chrUn_gl000237
                40531                 34474
41934                 45867
       chrUn_gl000238        chrUn_gl000239        chrUn_gl000240
chrUn_gl000241
                39939                 33824
41933                 42152
       chrUn_gl000242        chrUn_gl000243        chrUn_gl000244
chrUn_gl000245
                43523                 43341
39929                 36651
       chrUn_gl000246        chrUn_gl000247        chrUn_gl000248
chrUn_gl000249
                38154                 36422
39786                 38502

[[2]]
                 chr1                  chr2
chr3                  chr4
            249250621             243199373
198022430             191154276
                 chr5                  chr6
chr7                  chr8
            180915260             171115067
159138663             146364022
                 chr9                 chr10
chr11                 chr12
            141213431             135534747
135006516             133851895
                chr13                 chr14
chr15                 chr16
            115169878             107349540
102531392              90354753
                chr17                 chr18
chr19                 chr20
             81195210              78077248
59128983              63025520
                chr21                 chr22
chrX                  chrY
             48129895              51304566
155270560              59373566
                 chrM  chr1_gl000191_random  chr1_gl000192_random
chr4_gl000193_random
                16571                106433
547496                189789
 chr4_gl000194_random  chr7_gl000195_random  chr8_gl000196_random
chr8_gl000197_random
               191469                182896
38914                 37175
 chr9_gl000198_random  chr9_gl000199_random  chr9_gl000200_random
chr9_gl000201_random
                90085                169874
187035                 36148
chr11_gl000202_random chr17_gl000203_random chr17_gl000204_random
chr17_gl000205_random
                40103                 37498
81310                174588
chr17_gl000206_random chr18_gl000207_random chr19_gl000208_random
chr19_gl000209_random
                41001                  4262
92689                159169
chr21_gl000210_random        chrUn_gl000211        chrUn_gl000212
chrUn_gl000213
                27682                166566
186858                164239
       chrUn_gl000214        chrUn_gl000215        chrUn_gl000216
chrUn_gl000217
               137718                172545
172294                172149
       chrUn_gl000218        chrUn_gl000219        chrUn_gl000220
chrUn_gl000221
               161147                179198
161802                155397
       chrUn_gl000222        chrUn_gl000223        chrUn_gl000224
chrUn_gl000225
               186861                180455
179693                211173
       chrUn_gl000226        chrUn_gl000227        chrUn_gl000228
chrUn_gl000229
                15008                128374
129120                 19913
       chrUn_gl000230        chrUn_gl000231        chrUn_gl000232
chrUn_gl000233
                43691                 27386
40652                 45941
       chrUn_gl000234        chrUn_gl000235        chrUn_gl000236
chrUn_gl000237
                40531                 34474
41934                 45867
       chrUn_gl000238        chrUn_gl000239        chrUn_gl000240
chrUn_gl000241
                39939                 33824
41933                 42152
       chrUn_gl000242        chrUn_gl000243        chrUn_gl000244
chrUn_gl000245
                43523                 43341
39929                 36651
       chrUn_gl000246        chrUn_gl000247        chrUn_gl000248
chrUn_gl000249
                38154                 36422
39786                 38502



> seqlenghts(promoters_hg19)
Error: could not find function "seqlenghts"

**Comment by CharlesJB** [comment] 2016-03-07 18:45
Hello,

I compared the lengths of the chromosomes in the bam files with the regions in `promoters_hg19` and there does not appear to be regions outside any chromosome. The seqnames also appears to match.

Could you save the metagene object and send it to me by e-mail. I will need to analyze it to find what could be the problem.

To save the metagene object, after calling the `metagene$new` function:
```r
save(mg, file = "mg.RData")
```

You can send the `mg.RData` file to the e-mail listed on the Bioconductor web page:
https://bioconductor.org/packages/release/bioc/html/metagene.html

**Comment by CharlesJB** [comment] 2016-03-07 20:59
Hi Sarah,

I analyzed and it seems there is a bug with the `force_seqlevels` params. Normally, regions on alternative chromosomes such as `chr6_cox_hap2` that are present in promoters_hg19 but absent in the bam file should be removed when you use `force_seqlevels`.

I will create an Issue for this problem. Meanwhile, to avoid this error, you could work only with the standard chromosomes:
```r
bam_files = c("rep1_sorted.bam", "IN_rep1_sorted.bam")
regions <- keepStandardChromosomes(promoters_hg19)
mg <- metagene$new(regions=regions, bam_files=bam_files)
```

Does this help to avoid the error message?

**Comment by sjgeisler** [comment] 2016-03-07 21:31
It worked! I'm not getting the error message anymore.

Thanks again for help!

**Comment by CharlesJB** [comment] 2016-03-08 02:19
Great news! I will now close this issue. Don't hesitate to contact me again if you have other problems.

**Closed by CharlesJB** 2016-03-08 02:19 UTC
